# Generated by Django 4.1.5 on 2023-04-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehSS', '0003_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='date_time',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
